#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb  7 14:02:48 2020

@author: yueyingli
"""

###Given an array of integers and a number k, 
#where 1 <= k <= length of the array, 
#compute the maximum values of each subarray of length k.

#For example, given array = [10, 5, 2, 7, 8, 7] and k = 3, we should get: [10, 7, 8, 8], since:

#10 = max(10, 5, 2)
#7 = max(5, 2, 7)
#8 = max(2, 7, 8)
#8 = max(7, 8, 7)

def max_of_subarrays(lst, k):
    output = []
    for i in range(len(lst)-k+1):  #len也是不包含
        max_ = max(lst[i:i+k])   #尤其注意上面数序号，[a:b]不包含b！！！！
        print(max_)
        output.append(max_)
        
    return output

print(max_of_subarrays([10, 5, 2, 7, 8, 7],3))